name: Build project

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        type: choice
        options:
          - StandaloneWindows64
          - Android
          - iOS

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ inputs.platform }}
    runs-on: ${{ inputs.platform == 'iOS' && 'macos-latest' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ inputs.platform }}
          restore-keys: Library-
      - if: inputs.platform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1

      - if: inputs.platform == 'iOS'
        name: Install Apple Certificate
        uses: Apple-Actions/import-codesign-certs@v5.0.1
        with:
          p12-file-base64: ${{ secrets.IOS_P12_BASE64 }}
          p12-password: ${{ secrets.IOS_P12_PASSWORD }}
          create-keychain: true
          keychain-password: ${{ secrets.IOS_P12_PASSWORD }}

      - if: inputs.platform == 'iOS'
        name: Install Provisioning Profile
        uses: Apple-Actions/download-provisioning-profiles@v4.0.0
        with:
          bundle-id: 'com.stash.sdkdemo'
          profile-type: 'IOS_APP_STORE'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          androidExportType: 'androidAppBundle'
          androidKeystoreName: user.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
        with:
          targetPlatform: ${{ inputs.platform }}
          
      - if: inputs.platform == 'iOS'
        name: Create Export Options Plist
        run: |
          cat > build/iOS/iOS/exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
              <key>teamID</key>
              <string>${{ secrets.IOS_TEAM_ID }}</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.stash.sdkdemo</key>
                  <string>${{ secrets.IOS_PROVISIONING_PROFILE_NAME }}</string>
              </dict>
              <key>destination</key>
              <string>export</string>
          </dict>
          </plist>
          EOF

      - if: inputs.platform == 'iOS'
        name: Build and Archive iOS App
        run: |
          cd build/iOS/iOS
          
          # Set up code signing identity
          CERTIFICATE_NAME="${{ secrets.IOS_CERTIFICATE_NAME }}"
          TEAM_ID="${{ secrets.IOS_TEAM_ID }}"
          PROVISIONING_PROFILE_NAME="${{ secrets.IOS_PROVISIONING_PROFILE_NAME }}"
          
          # Clean any previous builds
          xcodebuild clean -project Unity-iPhone.xcodeproj -scheme Unity-iPhone
          
          # Resolve package dependencies
          xcodebuild -resolvePackageDependencies -project Unity-iPhone.xcodeproj -scheme Unity-iPhone
          
          # Archive the project with manual code signing
          xcodebuild archive \
            -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -configuration Release \
            -sdk iphoneos \
            -archivePath ./build/Unity-iPhone.xcarchive \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="$CERTIFICATE_NAME" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_NAME" \
            -allowProvisioningUpdates
          
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath ./build/Unity-iPhone.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath ./build
            
      - if: inputs.platform == 'iOS'
        name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v3
        with:
          app-path: 'build/iOS/iOS/build/Unity-iPhone.ipa'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ inputs.platform }}
          path: build/${{ inputs.platform }}
